%YAML:1.0

#> Problem Name (must be the same as the problem folder name)
problem_name: generalized_3views_4pts
problem_print_out_name: Generalized Three-View Relative Pose Problem using 4 Points

#> Reference: Ding, Yaqing, Chiang-Heng Chien, Viktor Larsson, Karl Åström, and Benjamin Kimia. 
#  "Minimal Solutions to Generalized Three-View Relative Pose Problem." 
#  In Proceedings of the IEEE/CVF International Conference on Computer Vision, pp. 8156-8164. 2023.

#> GPU-HC Settings
GPUHC_Type: P2C
GPUHC_Max_Steps: 200
GPUHC_Max_Correction_Steps: 100
GPUHC_Num_Of_Steps_to_Increase_Delta_t: 5

#> Problem spec
Num_Of_Vars: 12
Num_Of_Params: 45
Num_Of_Tracks: 583
dHdx_Max_Terms: 3
dHdx_Max_Parts: 3
dHdt_Max_Terms: 10
dHdt_Max_Parts: 4
Max_Order_Of_T: 2
Num_Of_Coeffs_From_Params: 66

#> RANSAC data
#RANSAC_Dataset: Synthetic / ICL-NUIM
# RANSAC_Dataset: ICL-NUIM
RANSAC_Dataset: None
