%YAML:1.0

#> Problem Name (must be the same as the problem folder name)
problem_name: generalized_3views_3orientedpoints
problem_print_out_name: Generalized Three-View Relative Pose Problem using 3 oriented-points

#> Reference: Ding, Yaqing, Chiang-Heng Chien

#> GPU-HC Settings
GPUHC_Type: P2C
GPUHC_Max_Steps: 200
GPUHC_Max_Correction_Steps: 200
GPUHC_Num_Of_Steps_to_Increase_Delta_t: 5

#> Problem spec
Num_Of_Vars: 15
Num_Of_Params: 54
Num_Of_Tracks: 840
P2C_Max_Terms_Per_Coeff: 12
P2C_Max_Params_Per_Term: 6
dHdx_Max_Terms: 40
dHdx_Max_Parts: 5
dHdt_Max_Terms: 100
dHdt_Max_Parts: 6
Max_Order_Of_T: 6
Num_Of_Coeffs_From_Params: 330

#> RANSAC data
#RANSAC_Dataset: Synthetic / ICL-NUIM
# RANSAC_Dataset: ICL-NUIM
RANSAC_Dataset: None
